schema: server/schema/schema_gen.graphql
exec:
  filename: server/graph/graph_gen.go
  package: graph
model:
  filename: server/model/model_gen.go
  package: model
resolver:
  filename: resolver.go
  type: Resolver
