schema: app/schema/schema_gen.graphql
exec:
  filename: app/graph/graph_gen.go
  package: graph
model:
  filename: app/model/model_gen.go
  package: model
resolver:
  filename: app/resolver_gen.go
  type: Resolver
