prod: false
app:
  port: 8080
  service:
    mssql:
      host: 127.0.0.1
      port: 1433
      username: platform
      password: p@sSw0rd
      database: platform
codegen:
  schema:
    path: schema.graphql
  output:
    dir: app/
