app:
  port: 8080
  service:
    mssql:
      host: 192.168.2.128
      port: 1433
      username: web
      password: byrke5l8byu
      database: nefco
codegen:
  schema:
    path: schema.graphql
  output:
    dir: app/
