codegen:
  schema:
    source: server/schema/schema.graphql
    generate: server/schema/schema_gen.graphql
  model: 
    package: server/model
  service:
    package: server/service
    filename: server/service/service_gen.go
