// Code generated by platform, DO NOT EDIT.

package app

import (
	graph "gitlab/nefco/platform/app/graph"
	service "gitlab/nefco/platform/app/service"
)

func init() {
	cfg := graph.Config{
		Resolvers: &resolver{},
	}
	schema = graph.NewExecutableSchema(cfg)
}

type resolver struct{}

func (r *resolver) Mutation() graph.MutationResolver {
	return &struct {
		*service.MSSQLUserMutationService
		service.PersonMutationService
		service.MaterialMutationService
	}{
		MSSQLUserMutationService: service.NewUserMutationService(),
		PersonMutationService:    service.NewPersonMutationService(),
		MaterialMutationService:  service.NewMaterialMutationService(),
	}
}

func (r *resolver) Query() graph.QueryResolver {
	return &struct {
		service.PersonQueryService
		service.MaterialQueryService
		*service.MSSQLUserQueryService
	}{
		MSSQLUserQueryService: service.NewUserQueryService(),
		PersonQueryService:    service.NewPersonQueryService(),
		MaterialQueryService:  service.NewMaterialQueryService(),
	}
}
func (r *resolver) User() graph.UserResolver {
	return service.NewUserRelationService()
}
