// Code generated by platform, DO NOT EDIT.

package app

import (
	graph "gitlab/nefco/platform/app/graph"
	service "gitlab/nefco/platform/app/service"
)

func init() {
	cfg := graph.Config{
		Resolvers: &resolver{},
	}
	schema = graph.NewExecutableSchema(cfg)
}

type resolver struct{}

func (r *resolver) Mutation() graph.MutationResolver {
	return &struct {
		service.UserMutationService
		service.MaterialMutationService
	} {
		UserMutationService: service.NewUserMutationService(),
		MaterialMutationService: service.NewMaterialMutationService(),
	}
}

func (r *resolver) Query() graph.QueryResolver {
	return &struct {
		service.UserQueryService
		service.MaterialQueryService
	} {
		MaterialQueryService: service.NewMaterialQueryService(),
		UserQueryService: service.NewUserQueryService(),
	}
}
func (r *resolver) Material() graph.MaterialResolver {
	return service.NewMaterialRelationService()
}

func (r *resolver) User() graph.UserResolver {
	return service.NewUserRelationService()
}
