// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Material struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type MaterialCreateInput struct {
	Name string `json:"name"`
}

type MaterialUpdateInput struct {
	Name string `json:"name"`
}

type MaterialWhereInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type MaterialWhereUniqueInput struct {
	ID int `json:"id"`
}

type User struct {
	ID        int        `json:"id"`
	Name      string     `json:"name"`
	Materials []Material `json:"materials"`
}

type UserCreateInput struct {
	Name string `json:"name"`
}

type UserUpdateInput struct {
	Name string `json:"name"`
}

type UserWhereInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserWhereUniqueInput struct {
	ID int `json:"id"`
}
