// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	fmt "fmt"
	io "io"
	strconv "strconv"
)

type Material struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type MaterialCreateInput struct {
	Name string `json:"name"`
}

type MaterialUpdateInput struct {
	Name string `json:"name"`
}

type MaterialWhereInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type MaterialWhereUniqueInput struct {
	ID int `json:"id"`
}

type RoleObject struct {
	ID     int        `json:"id"`
	Object string     `json:"object"`
	Access RoleAccess `json:"access"`
}

type RoleObjectCreateInput struct {
	Object string     `json:"object"`
	Access RoleAccess `json:"access"`
}

type RoleObjectUpdateInput struct {
	Object string     `json:"object"`
	Access RoleAccess `json:"access"`
}

type RoleObjectWhereInput struct {
	ID     int        `json:"id"`
	Object string     `json:"object"`
	Access RoleAccess `json:"access"`
}

type RoleObjectWhereUniqueInput struct {
	ID int `json:"id"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserCreateInput struct {
	Name string `json:"name"`
}

type UserUpdateInput struct {
	Name string `json:"name"`
}

type UserWhereInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserWhereUniqueInput struct {
	ID int `json:"id"`
}

// Уровни доступа
type RoleAccess string

const (
	// Создание
	RoleAccessCreate RoleAccess = "CREATE"
	// Чтение
	RoleAccessRead   RoleAccess = "READ"
	RoleAccessUpdate RoleAccess = "UPDATE"
	RoleAccessDelete RoleAccess = "DELETE"
)

func (e RoleAccess) IsValid() bool {
	switch e {
	case RoleAccessCreate, RoleAccessRead, RoleAccessUpdate, RoleAccessDelete:
		return true
	}
	return false
}

func (e RoleAccess) String() string {
	return string(e)
}

func (e *RoleAccess) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoleAccess(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoleAccess", str)
	}
	return nil
}

func (e RoleAccess) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
