// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID   string  `json:"id"`
	Text *string `json:"text"`
}

type PostCreateInput struct {
	Text *string `json:"text"`
}

type PostUpdateInput struct {
	Text *string `json:"text"`
}

type PostWhereInput struct {
	ID *string `json:"id"`
}

type PostWhereUniqueInput struct {
	ID *string `json:"id"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Posts []Post `json:"posts"`
}

type UserCreateInput struct {
	Name string `json:"name"`
}

type UserUpdateInput struct {
	Name string `json:"name"`
}

type UserWhereInput struct {
	ID *string `json:"id"`
}

type UserWhereUniqueInput struct {
	ID *string `json:"id"`
}
