codegen:
  schema:
    source: server/schema/schema.graphql
    generate: server/schema/schema_gen.graphql
  model: 
    filename: server/model/model_gen.go
  service:
    filename: server/service/service_gen.go