platform:
  services:
    mssql:
      host: 127.0.0.1
      port: 1433
codegen:
  services:
    mssql:
      dir: server/codegen/service/mssql/
  schema:
    source: server/schema/schema.graphql
    generate: server/schema/schema_gen.graphql
  model:
    dir: server/model/
  service:
    dir: server/service/
  server:
    config:
      dir: server/config/
