// Code generated by platform, DO NOT EDIT.

package {{ .PackageName }}

import (
{{- range $import := .Imports }}
	{{ $import.Alias }} "{{ $import.Path }}"
{{- end }}

    "github.com/jmoiron/sqlx"
)

