// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Node interface{}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
type UserCreateInput struct {
	Name string `json:"name"`
}
type UserUpdateInput struct {
	Name *string `json:"name"`
}
type UserWhereInput struct {
	ID      *string  `json:"id"`
	IDNot   *string  `json:"idNot"`
	IDIn    []string `json:"idIn"`
	IDNotIn []string `json:"idNotIn"`
}
type UserWhereUniqueInput struct {
	ID *string `json:"id"`
}
